export declare const MOON_CONFIG_KEY_ORDER: string[];
export declare const KIBANA_JSONC_FILENAME = "kibana.jsonc";
export declare const MOON_CONST: {
    MOON_CONFIG_FILE_NAME: string;
    TEMPLATE_FILE_NAME: string;
    EXTENSION_FILE_NAME: string;
    JEST_CONFIG_FILES: string[];
    ESLINT_CONFIG_FILES: string[];
    PROJECT_LAYER_UNKNOWN: string;
    DEFAULT_TOOLCHAIN: string;
    TAG_JEST_UNIT: string;
    TAG_DEV: string;
    TAG_PROD: string;
    TAG_PACKAGE: string;
    TAG_PLUGIN: string;
    TAG_GROUP: string;
    TASK_NAME_JEST: string;
    TASK_NAME_JEST_CI: string;
    TASK_NAME_LINT: string;
    FILE_GROUP_SRC: string;
};
