export declare enum NEW_FEATURES_TOUR_STORAGE_KEYS {
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE",
    ANONYMIZED_VALUES_AND_CITATIONS = "ANONYMIZED_VALUES_AND_CITATIONS",
    ELASTIC_LLM_USAGE_ATTACK_DISCOVERY = "ELASTIC_LLM_USAGE_ATTACK_DISCOVERY",
    ELASTIC_LLM_USAGE_ATTACK_DISCOVERY_FLYOUT = "ELASTIC_LLM_USAGE_ATTACK_DISCOVERY_FLYOUT",
    ELASTIC_LLM_USAGE_AUTOMATIC_TROUBLESHOOTING = "ELASTIC_LLM_USAGE_AUTOMATIC_TROUBLESHOOTING",
    CONVERSATION_CONNECTOR_ELASTIC_LLM = "CONVERSATION_CONNECTOR_ELASTIC_LLM",
    AGENT_BUILDER_TOUR = "AGENT_BUILDER_TOUR"
}
export declare const NEW_TOUR_FEATURES_TOUR_STORAGE_KEYS: Record<NEW_FEATURES_TOUR_STORAGE_KEYS, string>;
