export declare const CA_CERT_PATH: string;
export declare const CA_TRUSTED_FINGERPRINT = "F71F73085975FD977339A1909EBFE2DF40DB255E0D5BB56FC37246BF383FFC84";
export declare const ES_KEY_PATH: string;
export declare const ES_CERT_PATH: string;
export declare const ES_P12_PATH: string;
export declare const ES_P12_PASSWORD = "storepass";
export declare const ES_EMPTYPASSWORD_P12_PATH: string;
export declare const ES_NOPASSWORD_P12_PATH: string;
export declare const KBN_KEY_PATH: string;
export declare const KBN_CERT_PATH: string;
export declare const KBN_P12_PATH: string;
export declare const KBN_P12_PASSWORD = "storepass";
export declare const FLEET_SERVER_KEY_PATH: string;
export declare const FLEET_SERVER_CERT_PATH: string;
export declare const FLEET_SERVER_P12_PATH: string;
export declare const FLEET_SERVER_P12_PASSWORD = "storepass";
