import type { ANONYMIZATION_TAB, CONNECTORS_TAB, CONVERSATIONS_TAB, EVALUATION_TAB, KNOWLEDGE_BASE_TAB, QUICK_PROMPTS_TAB, SYSTEM_PROMPTS_TAB } from './const';
export type ModalSettingsTabs = typeof QUICK_PROMPTS_TAB | typeof SYSTEM_PROMPTS_TAB;
export type ManagementSettingsTabs = typeof CONVERSATIONS_TAB | typeof QUICK_PROMPTS_TAB | typeof SYSTEM_PROMPTS_TAB | typeof ANONYMIZATION_TAB | typeof KNOWLEDGE_BASE_TAB | typeof EVALUATION_TAB | typeof CONNECTORS_TAB;
